Repository paralect/ship, pull requests merged in 2023-12, with the labels that each got.

#245 Add packages directory to the deployment triggers
  deploy/aws/.github/workflows/api-production.yml
  deploy/aws/.github/workflows/api-staging.yml
  deploy/aws/.github/workflows/web-production.yml
  deploy/aws/.github/workflows/web-staging.yml
  deploy/digital-ocean-apps/koa/.github/workflows/api-production.yml
  deploy/digital-ocean-apps/koa/.github/workflows/api-staging.yml
  deploy/digital-ocean-apps/koa/.github/workflows/web-production.yml
  deploy/digital-ocean-apps/koa/.github/workflows/web-staging.yml
  deploy/digital-ocean/.github/workflows/api-production.yml
  deploy/digital-ocean/.github/workflows/api-staging.yml
  deploy/digital-ocean/.github/workflows/web-production.yml
  deploy/digital-ocean/.github/workflows/web-staging.yml
  template/.github/workflows/run-tests.yml
Labels: Bug, Reviewed

#246 Fix setQueryData in profile update
  examples/public-docs/apps/web/src/pages/profile/index.page.tsx
  examples/stripe-subscriptions/apps/web/src/pages/profile/index.page.tsx
  template/apps/web/src/pages/profile/index.page.tsx
Labels: Reviewed, Improvement

#247 Add attachments to emails
  template/apps/api/src/services/email/email.service.ts
  template/apps/api/src/services/email/email.types.ts
Labels: Reviewed, Improvement

#248 Remove redundant awaits
  examples/public-docs/apps/web/src/pages/profile/components/PhotoUpload/index.tsx
  examples/stripe-subscriptions/apps/web/src/pages/profile/components/file-upload/index.tsx
  template/apps/web/src/pages/profile/components/PhotoUpload/index.tsx
Labels: Reviewed, Improvement

#251 Add documentation for web
  docs/mint.json
  docs/web/calling-api.mdx
  docs/web/environment-variables.mdx
  docs/web/forms.mdx
  docs/web/overview.mdx
  docs/web/routing.mdx
  docs/web/services.mdx
  docs/web/styling.mdx
  template/apps/web/.storybook/preview.js
  template/apps/web/src/pages/_app/index.tsx
  template/apps/web/src/theme/index.ts
  template/pnpm-lock.yaml
Labels: docs

#252 Redis Improvements
  template/apps/api/src/config/index.ts
  template/apps/api/src/io-emitter.ts
  template/apps/api/src/redis-client.ts
  template/apps/api/src/services/socket/socket.service.ts
Labels: template, Improvement

#253 fix: rollback nextjs version
  template/apps/web/package.json
  template/package.json
  template/pnpm-lock.yaml
Labels: Bug, Reviewed

#254 fix: rollback nextjs version
  pnpm-lock.yaml
  template/apps/web/package.json
  template/package.json
Labels: Bug
