Repository paralect/ship, pull requests merged in 2025-07, with the labels that each got.

#369 Update build templates for PR checks
  .github/workflows/build-api.yml
  .github/workflows/build-web.yml
Labels: Improvement

#370 Update mongodb driver to the latest version and fix all vulnerabilities
  packages/node-mongo/package-lock.json
  packages/node-mongo/package.json
Labels: node-mongo

#374 Update mongodb to v8.0 in docker-compose file
  template/docker-compose.yml
Labels: Dependencies

#376 fix: Update setup.sh, wait for database to start
  template/bin/setup.sh
Labels: Approved, template, Improvement

#377 Update typescript version to 5.8.3
  template/apps/api/Dockerfile
  template/apps/api/Dockerfile.migrator
  template/apps/api/Dockerfile.scheduler
  template/apps/api/src/services/google/google.service.ts
  template/pnpm-lock.yaml
  template/pnpm-workspace.yaml
Labels: Dependencies
